[tool.poetry]
name = "blog"
version = "0.1.0"
description = "Krystian Safjan blog"
authors = ["Krystian Safjan <ksafjan@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pelican = "^4.5.4"
pelican-jupyter = "^0.10.0"
pylint = "^2.6.0"
typogrify = "^2.0.7"
markdown = "^3.3.3"
ipython = "^7.20.0"
nbconvert = "^6.0.7"
jupyter = "^1.0.0"
beautifulsoup4 = "^4.9.3"
pelican-readtime = "^0.2.0"
pelican-neighbors = "^1.1.0"
pelican-related-posts = "^1.0.0"
pelican-render-math = "^1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
